# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# grouping_test.py
# Created on: 2014-08-27 09:25:23.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import sys
import imp

psu_app = imp.load_source('psu_app', 'C:\\Users\\zwhitman\\Documents\\census\\psu_cluster_app\\psu_app.py')
import psu_app
from psu_app import *
import os
from subprocess import Popen


# Local variables:
arcpy.env.workspace = psu_app.fullpath_tmp_state_folder1
Alabama_22c8be8b_4979_402c_9d69_95444866a567_shp = "C:\\Users\\zwhitman\\Documents\\census\\psu_app\\test_run\\tmp\\Alabama_713c74b2_5250_4454_99f8_8a320b351ecb\\Alabama_22c8be8b_4979_402c_9d69_95444866a567.shp"
Alabama_22c8be8b_4979_402c_9_shp = "C:\\Users\\zwhitman\\Documents\\census\\psu_app\\test_run\\tmp\\Alabama_713c74b2_5250_4454_99f8_8a320b351ecb\\Alabama_22c8be8b_4979_402c_9_standalone23.shp"
GroupingOutput2_pdf = fullpath_tmp_state_folder1+"GroupingOutput2_standalone23.pdf"

print "testing"

try:
    # Process: Grouping Analysis
    arcpy.GroupingAnalysis_stats(psu_app.fullpath_tmp_state_folder1, "COUNTYFP_1", psu_app.name4, "2", "ALANDSQM", "CONTIGUITY_EDGES_CORNERS", "EUCLIDEAN", "0", "", "FIND_SEED_LOCATIONS", "", GroupingOutput2_pdf, "DO_NOT_EVALUATE")

    print "grouping is done"

    # Process: Add Field
    arcpy.AddField_management(Alabama_22c8be8b_4979_402c_9d69_95444866a567_shp, "test_1", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

    var = 'test'+str(2)

    arcpy.AddField_management(Alabama_22c8be8b_4979_402c_9d69_95444866a567_shp, var, "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
    print "It worked"
except StandardError:
    print "error"
    print sys.argv


